tasks:
  - init: npm install
    command: |
      export HMR_HOST=`gp url 3000`
      npm run dev
ports:
  - port: 3000
    onOpen: open-browser
vscode:
  extensions:
    - ferrielmelarpis.vscode-css-modules-syntax-highlighter
    - zardoy.fix-all-json
    - fivethree.vscode-svelte-snippets
    - formulahendry.auto-close-tag
    - steoates.autoimport
    - redwan-hossain.auto-rename-tag-clone
    - CoenraadS.bracket-pair-colorizer
    - ms-azuretools.vscode-docker
    - mhutchie.git-graph
    - antfu.iconify
    - malipetek.liquivelte
    - Equinusocio.vsc-material-theme
    - equinusocio.vsc-material-theme-icons
    - christian-kohler.npm-intellisense
    - whizkydee.material-palenight-theme
    - Prisma.prisma
    - syler.sass-indented
    - bradlc.vscode-tailwindcss
    - gengjiawen.vscode-postfix-ts
    - ms-vscode.vscode-typescript-tslint-plugin
    - eamodio.tsl-problem-matcher
    - svelte.svelte-vscode

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true